name: GOPAD
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9893413402605802
  lightness: 0.3446377241052687
  saturation: 0.7913905419409275
  rhythmicContrast: 0.016372814774513245
purpose: []
